// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYuJhrTTEA0ui782coD8ehbOZwFOPZQ6A',
    appId: '1:230074448899:web:f329eb2065392a53c56236',
    messagingSenderId: '230074448899',
    projectId: 'zipbuzz-dev',
    authDomain: 'zipbuzz-dev.firebaseapp.com',
    databaseURL: 'https://zipbuzz-dev-default-rtdb.firebaseio.com',
    storageBucket: 'zipbuzz-dev.appspot.com',
    measurementId: 'G-8Q2TKC39JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgkOsPa4jnlY687eQGGIOy0jYZ-NdPtD8',
    appId: '1:230074448899:android:7f90c3ed745396e4c56236',
    messagingSenderId: '230074448899',
    projectId: 'zipbuzz-dev',
    databaseURL: 'https://zipbuzz-dev-default-rtdb.firebaseio.com',
    storageBucket: 'zipbuzz-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkJTmQGMuw4eu0fWAnEEe-P29By9PRADk',
    appId: '1:230074448899:ios:f9ba1200c2738751c56236',
    messagingSenderId: '230074448899',
    projectId: 'zipbuzz-dev',
    databaseURL: 'https://zipbuzz-dev-default-rtdb.firebaseio.com',
    storageBucket: 'zipbuzz-dev.appspot.com',
    androidClientId: '230074448899-iv1f86sgv0gjbeca0673ookf8grpmect.apps.googleusercontent.com',
    iosClientId: '230074448899-0bvjvaopdo5fp1idhojrji253q8pjo6s.apps.googleusercontent.com',
    iosBundleId: 'com.zipbuzz.me',
  );
}
