// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnrm3FPGzLcP1g_U0IZrd39o8qUqgsk5o',
    appId: '1:892338366790:web:38ff4d54d4a1bb85469d47',
    messagingSenderId: '892338366790',
    projectId: 'zipbuzz-prod',
    authDomain: 'zipbuzz-prod.firebaseapp.com',
    databaseURL: 'https://zipbuzz-prod-default-rtdb.firebaseio.com',
    storageBucket: 'zipbuzz-prod.appspot.com',
    measurementId: 'G-1CCE22HZC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJe8yovuIgvsHXFtlGmKDMZUhF5k1AItI',
    appId: '1:892338366790:android:167fbaae811e7d51469d47',
    messagingSenderId: '892338366790',
    projectId: 'zipbuzz-prod',
    databaseURL: 'https://zipbuzz-prod-default-rtdb.firebaseio.com',
    storageBucket: 'zipbuzz-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsb9CbE0qWLnheRrpd4tJZGxP_i_d06fw',
    appId: '1:892338366790:ios:8f3af7b612e01461469d47',
    messagingSenderId: '892338366790',
    projectId: 'zipbuzz-prod',
    databaseURL: 'https://zipbuzz-prod-default-rtdb.firebaseio.com',
    storageBucket: 'zipbuzz-prod.appspot.com',
    androidClientId: '892338366790-3bpg24tpe3h9n7b13kf6ghk1ius4f2ad.apps.googleusercontent.com',
    iosClientId: '892338366790-6k3qbi6iufgotc0oqljc5j16l546hm76.apps.googleusercontent.com',
    iosBundleId: 'com.zipbuzz.me',
  );
}